/* Slingscold.c generated by valac 0.40.23, the Vala compiler
 * generated from Slingscold.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <libpeas/peas.h>
#include <plugin.h>
#include <stdlib.h>
#include <string.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>


#define SLINGSCOLD_APPLET_TYPE_PLUGIN (slingscold_applet_plugin_get_type ())
#define SLINGSCOLD_APPLET_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SLINGSCOLD_APPLET_TYPE_PLUGIN, SlingscoldAppletPlugin))
#define SLINGSCOLD_APPLET_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SLINGSCOLD_APPLET_TYPE_PLUGIN, SlingscoldAppletPluginClass))
#define SLINGSCOLD_APPLET_IS_PLUGIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SLINGSCOLD_APPLET_TYPE_PLUGIN))
#define SLINGSCOLD_APPLET_IS_PLUGIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SLINGSCOLD_APPLET_TYPE_PLUGIN))
#define SLINGSCOLD_APPLET_PLUGIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SLINGSCOLD_APPLET_TYPE_PLUGIN, SlingscoldAppletPluginClass))

typedef struct _SlingscoldAppletPlugin SlingscoldAppletPlugin;
typedef struct _SlingscoldAppletPluginClass SlingscoldAppletPluginClass;
typedef struct _SlingscoldAppletPluginPrivate SlingscoldAppletPluginPrivate;
enum  {
	SLINGSCOLD_APPLET_PLUGIN_0_PROPERTY,
	SLINGSCOLD_APPLET_PLUGIN_NUM_PROPERTIES
};
static GParamSpec* slingscold_applet_plugin_properties[SLINGSCOLD_APPLET_PLUGIN_NUM_PROPERTIES];

#define SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET (slingscold_applet_slingscold_applet_get_type ())
#define SLINGSCOLD_APPLET_SLINGSCOLD_APPLET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldApplet))
#define SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldAppletClass))
#define SLINGSCOLD_APPLET_IS_SLINGSCOLD_APPLET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET))
#define SLINGSCOLD_APPLET_IS_SLINGSCOLD_APPLET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET))
#define SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldAppletClass))

typedef struct _SlingscoldAppletSlingscoldApplet SlingscoldAppletSlingscoldApplet;
typedef struct _SlingscoldAppletSlingscoldAppletClass SlingscoldAppletSlingscoldAppletClass;
typedef struct _SlingscoldAppletSlingscoldAppletPrivate SlingscoldAppletSlingscoldAppletPrivate;
enum  {
	SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_0_PROPERTY,
	SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_UUID_PROPERTY,
	SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_NUM_PROPERTIES
};
static GParamSpec* slingscold_applet_slingscold_applet_properties[SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _SlingscoldAppletPlugin {
	PeasExtensionBase parent_instance;
	SlingscoldAppletPluginPrivate * priv;
};

struct _SlingscoldAppletPluginClass {
	PeasExtensionBaseClass parent_class;
};

struct _SlingscoldAppletSlingscoldApplet {
	BudgieApplet parent_instance;
	SlingscoldAppletSlingscoldAppletPrivate * priv;
};

struct _SlingscoldAppletSlingscoldAppletClass {
	BudgieAppletClass parent_class;
};

struct _SlingscoldAppletSlingscoldAppletPrivate {
	GtkButton* widget;
	gchar* _uuid;
	GtkImage* img;
	GtkLabel* label;
	BudgiePanelPosition panel_position;
	gint pixel_size;
};


static gpointer slingscold_applet_plugin_parent_class = NULL;
static BudgiePluginIface * slingscold_applet_plugin_budgie_plugin_parent_iface = NULL;
static GType slingscold_applet_plugin_type_id = 0;
static gpointer slingscold_applet_slingscold_applet_parent_class = NULL;
static GType slingscold_applet_slingscold_applet_type_id = 0;

GType slingscold_applet_plugin_register_type (GTypeModule * module);
GType slingscold_applet_plugin_get_type (void) G_GNUC_CONST;
static BudgieApplet* slingscold_applet_plugin_real_get_panel_widget (BudgiePlugin* base,
                                                              const gchar* uuid);
SlingscoldAppletSlingscoldApplet* slingscold_applet_slingscold_applet_new (const gchar* uuid);
SlingscoldAppletSlingscoldApplet* slingscold_applet_slingscold_applet_construct (GType object_type,
                                                                                 const gchar* uuid);
GType slingscold_applet_slingscold_applet_register_type (GTypeModule * module);
GType slingscold_applet_slingscold_applet_get_type (void) G_GNUC_CONST;
SlingscoldAppletPlugin* slingscold_applet_plugin_new (void);
SlingscoldAppletPlugin* slingscold_applet_plugin_construct (GType object_type);
#define SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldAppletPrivate))
static gboolean slingscold_applet_slingscold_applet_real_supports_settings (BudgieApplet* base);
static gboolean __lambda4_ (SlingscoldAppletSlingscoldApplet* self,
                     GdkEventButton* e);
static gboolean ___lambda4__gtk_widget_button_press_event (GtkWidget* _sender,
                                                    GdkEventButton* event,
                                                    gpointer self);
static void slingscold_applet_slingscold_applet_real_invoke_action (BudgieApplet* base,
                                                             BudgiePanelAction action);
const gchar* slingscold_applet_slingscold_applet_get_uuid (SlingscoldAppletSlingscoldApplet* self);
void slingscold_applet_slingscold_applet_set_uuid (SlingscoldAppletSlingscoldApplet* self,
                                                   const gchar* value);
static void slingscold_applet_slingscold_applet_finalize (GObject * obj);
static void _vala_slingscold_applet_slingscold_applet_get_property (GObject * object,
                                                             guint property_id,
                                                             GValue * value,
                                                             GParamSpec * pspec);
static void _vala_slingscold_applet_slingscold_applet_set_property (GObject * object,
                                                             guint property_id,
                                                             const GValue * value,
                                                             GParamSpec * pspec);
void peas_register_types (GTypeModule* module);
GType slingscold_applet_plugin_register_type (GTypeModule * module);
GType slingscold_applet_slingscold_applet_register_type (GTypeModule * module);


static BudgieApplet*
slingscold_applet_plugin_real_get_panel_widget (BudgiePlugin* base,
                                                const gchar* uuid)
{
	SlingscoldAppletPlugin * self;
	BudgieApplet* result = NULL;
	SlingscoldAppletSlingscoldApplet* _tmp0_;
	self = (SlingscoldAppletPlugin*) base;
	g_return_val_if_fail (uuid != NULL, NULL);
	_tmp0_ = slingscold_applet_slingscold_applet_new (uuid);
	g_object_ref_sink (_tmp0_);
	result = (BudgieApplet*) _tmp0_;
	return result;
}


SlingscoldAppletPlugin*
slingscold_applet_plugin_construct (GType object_type)
{
	SlingscoldAppletPlugin * self = NULL;
	self = (SlingscoldAppletPlugin*) g_object_new (object_type, NULL);
	return self;
}


SlingscoldAppletPlugin*
slingscold_applet_plugin_new (void)
{
	return slingscold_applet_plugin_construct (SLINGSCOLD_APPLET_TYPE_PLUGIN);
}


static void
slingscold_applet_plugin_class_init (SlingscoldAppletPluginClass * klass)
{
	slingscold_applet_plugin_parent_class = g_type_class_peek_parent (klass);
}


static void
slingscold_applet_plugin_budgie_plugin_interface_init (BudgiePluginIface * iface)
{
	slingscold_applet_plugin_budgie_plugin_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_panel_widget = (BudgieApplet* (*) (BudgiePlugin*, const gchar*)) slingscold_applet_plugin_real_get_panel_widget;
}


static void
slingscold_applet_plugin_instance_init (SlingscoldAppletPlugin * self)
{
}


GType
slingscold_applet_plugin_get_type (void)
{
	return slingscold_applet_plugin_type_id;
}


GType
slingscold_applet_plugin_register_type (GTypeModule * module)
{
	static const GTypeInfo g_define_type_info = { sizeof (SlingscoldAppletPluginClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) slingscold_applet_plugin_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SlingscoldAppletPlugin), 0, (GInstanceInitFunc) slingscold_applet_plugin_instance_init, NULL };
	static const GInterfaceInfo budgie_plugin_info = { (GInterfaceInitFunc) slingscold_applet_plugin_budgie_plugin_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	slingscold_applet_plugin_type_id = g_type_module_register_type (module, peas_extension_base_get_type (), "SlingscoldAppletPlugin", &g_define_type_info, 0);
	g_type_module_add_interface (module, slingscold_applet_plugin_type_id, budgie_plugin_get_type (), &budgie_plugin_info);
	return slingscold_applet_plugin_type_id;
}


static gboolean
slingscold_applet_slingscold_applet_real_supports_settings (BudgieApplet* base)
{
	SlingscoldAppletSlingscoldApplet * self;
	gboolean result = FALSE;
	self = (SlingscoldAppletSlingscoldApplet*) base;
	result = FALSE;
	return result;
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


static gboolean
__lambda4_ (SlingscoldAppletSlingscoldApplet* self,
            GdkEventButton* e)
{
	gboolean result = FALSE;
	guint _tmp0_;
	GError* _inner_error0_ = NULL;
	g_return_val_if_fail (e != NULL, FALSE);
	_tmp0_ = e->button;
	if (_tmp0_ != ((guint) 1)) {
		result = GDK_EVENT_PROPAGATE;
		return result;
	}
	g_spawn_command_line_async ("slingscold", &_inner_error0_);
	if (G_UNLIKELY (_inner_error0_ != NULL)) {
		gboolean _tmp1_ = FALSE;
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
		g_clear_error (&_inner_error0_);
		return _tmp1_;
	}
	result = GDK_EVENT_STOP;
	return result;
}


static gboolean
___lambda4__gtk_widget_button_press_event (GtkWidget* _sender,
                                           GdkEventButton* event,
                                           gpointer self)
{
	gboolean result;
	result = __lambda4_ ((SlingscoldAppletSlingscoldApplet*) self, event);
	return result;
}


SlingscoldAppletSlingscoldApplet*
slingscold_applet_slingscold_applet_construct (GType object_type,
                                               const gchar* uuid)
{
	SlingscoldAppletSlingscoldApplet * self = NULL;
	GtkButton* _tmp0_;
	GtkButton* _tmp1_;
	GtkImage* _tmp2_;
	GtkImage* _tmp3_;
	gint _tmp4_;
	GtkImage* _tmp5_;
	GtkImage* _tmp6_;
	GtkBox* layout = NULL;
	GtkBox* _tmp7_;
	GtkImage* _tmp8_;
	GtkLabel* _tmp9_;
	GtkLabel* _tmp10_;
	GtkLabel* _tmp11_;
	GtkButton* _tmp12_;
	GtkStyleContext* st = NULL;
	GtkButton* _tmp13_;
	GtkStyleContext* _tmp14_;
	GtkStyleContext* _tmp15_;
	GtkButton* _tmp16_;
	GtkButton* _tmp17_;
	g_return_val_if_fail (uuid != NULL, NULL);
	self = (SlingscoldAppletSlingscoldApplet*) g_object_new (object_type, "uuid", uuid, NULL);
	_tmp0_ = (GtkButton*) gtk_button_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->widget);
	self->priv->widget = _tmp0_;
	_tmp1_ = self->priv->widget;
	gtk_button_set_relief (_tmp1_, GTK_RELIEF_NONE);
	_tmp2_ = (GtkImage*) gtk_image_new_from_icon_name ("view-grid-symbolic", (GtkIconSize) GTK_ICON_SIZE_INVALID);
	g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->img);
	self->priv->img = _tmp2_;
	_tmp3_ = self->priv->img;
	_tmp4_ = self->priv->pixel_size;
	gtk_image_set_pixel_size (_tmp3_, _tmp4_);
	_tmp5_ = self->priv->img;
	gtk_widget_set_no_show_all ((GtkWidget*) _tmp5_, TRUE);
	_tmp6_ = self->priv->img;
	gtk_widget_set_visible ((GtkWidget*) _tmp6_, TRUE);
	_tmp7_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp7_);
	layout = _tmp7_;
	_tmp8_ = self->priv->img;
	gtk_box_pack_start (layout, (GtkWidget*) _tmp8_, TRUE, TRUE, (guint) 0);
	_tmp9_ = (GtkLabel*) gtk_label_new ("");
	g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp9_;
	_tmp10_ = self->priv->label;
	gtk_widget_set_halign ((GtkWidget*) _tmp10_, GTK_ALIGN_START);
	_tmp11_ = self->priv->label;
	gtk_box_pack_start (layout, (GtkWidget*) _tmp11_, TRUE, TRUE, (guint) 3);
	_tmp12_ = self->priv->widget;
	gtk_container_add ((GtkContainer*) _tmp12_, (GtkWidget*) layout);
	_tmp13_ = self->priv->widget;
	_tmp14_ = gtk_widget_get_style_context ((GtkWidget*) _tmp13_);
	_tmp15_ = _g_object_ref0 (_tmp14_);
	st = _tmp15_;
	gtk_style_context_add_class (st, "budgie-menu-launcher");
	gtk_style_context_add_class (st, "panel-button");
	g_object_set ((BudgieApplet*) self, "supported-actions", BUDGIE_PANEL_ACTION_MENU, NULL);
	_tmp16_ = self->priv->widget;
	g_signal_connect_object ((GtkWidget*) _tmp16_, "button-press-event", (GCallback) ___lambda4__gtk_widget_button_press_event, self, 0);
	_tmp17_ = self->priv->widget;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp17_);
	gtk_widget_show_all ((GtkWidget*) self);
	_g_object_unref0 (st);
	_g_object_unref0 (layout);
	return self;
}


SlingscoldAppletSlingscoldApplet*
slingscold_applet_slingscold_applet_new (const gchar* uuid)
{
	return slingscold_applet_slingscold_applet_construct (SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, uuid);
}


static void
slingscold_applet_slingscold_applet_real_invoke_action (BudgieApplet* base,
                                                        BudgiePanelAction action)
{
	SlingscoldAppletSlingscoldApplet * self;
	GError* _inner_error0_ = NULL;
	self = (SlingscoldAppletSlingscoldApplet*) base;
	if ((action & BUDGIE_PANEL_ACTION_MENU) != 0) {
		g_spawn_command_line_async ("slingscold", &_inner_error0_);
		if (G_UNLIKELY (_inner_error0_ != NULL)) {
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error0_->message, g_quark_to_string (_inner_error0_->domain), _inner_error0_->code);
			g_clear_error (&_inner_error0_);
			return;
		}
	}
}


const gchar*
slingscold_applet_slingscold_applet_get_uuid (SlingscoldAppletSlingscoldApplet* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_uuid;
	result = _tmp0_;
	return result;
}


void
slingscold_applet_slingscold_applet_set_uuid (SlingscoldAppletSlingscoldApplet* self,
                                              const gchar* value)
{
	g_return_if_fail (self != NULL);
	if (g_strcmp0 (value, slingscold_applet_slingscold_applet_get_uuid (self)) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_uuid);
		self->priv->_uuid = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, slingscold_applet_slingscold_applet_properties[SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_UUID_PROPERTY]);
	}
}


static void
slingscold_applet_slingscold_applet_class_init (SlingscoldAppletSlingscoldAppletClass * klass)
{
	slingscold_applet_slingscold_applet_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SlingscoldAppletSlingscoldAppletPrivate));
	((BudgieAppletClass *) klass)->supports_settings = (gboolean (*) (BudgieApplet*)) slingscold_applet_slingscold_applet_real_supports_settings;
	((BudgieAppletClass *) klass)->invoke_action = (void (*) (BudgieApplet*, BudgiePanelAction)) slingscold_applet_slingscold_applet_real_invoke_action;
	G_OBJECT_CLASS (klass)->get_property = _vala_slingscold_applet_slingscold_applet_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_slingscold_applet_slingscold_applet_set_property;
	G_OBJECT_CLASS (klass)->finalize = slingscold_applet_slingscold_applet_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_UUID_PROPERTY, slingscold_applet_slingscold_applet_properties[SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_UUID_PROPERTY] = g_param_spec_string ("uuid", "uuid", "uuid", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void
slingscold_applet_slingscold_applet_instance_init (SlingscoldAppletSlingscoldApplet * self)
{
	self->priv = SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_GET_PRIVATE (self);
	self->priv->panel_position = BUDGIE_PANEL_POSITION_BOTTOM;
	self->priv->pixel_size = 32;
}


static void
slingscold_applet_slingscold_applet_finalize (GObject * obj)
{
	SlingscoldAppletSlingscoldApplet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldApplet);
	_g_object_unref0 (self->priv->widget);
	_g_free0 (self->priv->_uuid);
	_g_object_unref0 (self->priv->img);
	_g_object_unref0 (self->priv->label);
	G_OBJECT_CLASS (slingscold_applet_slingscold_applet_parent_class)->finalize (obj);
}


GType
slingscold_applet_slingscold_applet_get_type (void)
{
	return slingscold_applet_slingscold_applet_type_id;
}


GType
slingscold_applet_slingscold_applet_register_type (GTypeModule * module)
{
	static const GTypeInfo g_define_type_info = { sizeof (SlingscoldAppletSlingscoldAppletClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) slingscold_applet_slingscold_applet_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SlingscoldAppletSlingscoldApplet), 0, (GInstanceInitFunc) slingscold_applet_slingscold_applet_instance_init, NULL };
	slingscold_applet_slingscold_applet_type_id = g_type_module_register_type (module, budgie_applet_get_type (), "SlingscoldAppletSlingscoldApplet", &g_define_type_info, 0);
	return slingscold_applet_slingscold_applet_type_id;
}


static void
_vala_slingscold_applet_slingscold_applet_get_property (GObject * object,
                                                        guint property_id,
                                                        GValue * value,
                                                        GParamSpec * pspec)
{
	SlingscoldAppletSlingscoldApplet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldApplet);
	switch (property_id) {
		case SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_UUID_PROPERTY:
		g_value_set_string (value, slingscold_applet_slingscold_applet_get_uuid (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void
_vala_slingscold_applet_slingscold_applet_set_property (GObject * object,
                                                        guint property_id,
                                                        const GValue * value,
                                                        GParamSpec * pspec)
{
	SlingscoldAppletSlingscoldApplet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, SLINGSCOLD_APPLET_TYPE_SLINGSCOLD_APPLET, SlingscoldAppletSlingscoldApplet);
	switch (property_id) {
		case SLINGSCOLD_APPLET_SLINGSCOLD_APPLET_UUID_PROPERTY:
		slingscold_applet_slingscold_applet_set_uuid (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


void
peas_register_types (GTypeModule* module)
{
	PeasObjectModule* objmodule = NULL;
	PeasObjectModule* _tmp0_;
	g_return_if_fail (module != NULL);
	slingscold_applet_plugin_register_type (module);
	slingscold_applet_slingscold_applet_register_type (module);
	_tmp0_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_TYPE (module, peas_object_module_get_type ()) ? ((PeasObjectModule*) module) : NULL);
	objmodule = _tmp0_;
	peas_object_module_register_extension_type (objmodule, budgie_plugin_get_type (), SLINGSCOLD_APPLET_TYPE_PLUGIN);
	_g_object_unref0 (objmodule);
}



